-- Enable Row Level Security
ALTER TABLE
  IF EXISTS clubs ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  IF EXISTS players ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  IF EXISTS matches ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  IF EXISTS match_players ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  IF EXISTS news ENABLE ROW LEVEL SECURITY;

-- Create tables
CREATE TABLE IF NOT EXISTS clubs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  logo TEXT,
  played INTEGER DEFAULT 0,
  won INTEGER DEFAULT 0,
  drawn INTEGER DEFAULT 0,
  lost INTEGER DEFAULT 0,
  goals_for INTEGER DEFAULT 0,
  goals_against INTEGER DEFAULT 0,
  points INTEGER DEFAULT 0,
  is_mcdo_pool BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc' :: TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc' :: TEXT, NOW()) NOT NULL
);

-- Create RLS policies
CREATE POLICY "Enable read access for all users" ON clubs FOR
SELECT
  USING (true);

CREATE POLICY "Enable insert for all users" ON clubs FOR
INSERT
  WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON clubs FOR
UPDATE
  USING (
    CASE
      WHEN id = 1 THEN -- For KDA club, only allow updating stats
      (
        OLD.name = NEW.name
        AND OLD.logo = NEW.logo
        AND OLD.is_mcdo_pool = NEW.is_mcdo_pool
      )
      ELSE true
    END
  );

CREATE POLICY "Enable delete for all users" ON clubs FOR DELETE USING (id != 1);

-- Insert initial KDA club if not exists
INSERT INTO
  clubs (
    id,
    name,
    logo,
    played,
    won,
    drawn,
    lost,
    goals_for,
    goals_against,
    points,
    is_mcdo_pool
  )
VALUES
  (
    1,
    'KDA Sporting Club',
    '/kda.jpg',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    true
  ) ON CONFLICT (id) DO NOTHING;

-- Add is_mcdo_pool column if it doesn't exist
DO $ $ BEGIN IF NOT EXISTS (
  SELECT
  FROM
    information_schema.columns
  WHERE
    table_name = 'clubs'
    AND column_name = 'is_mcdo_pool'
) THEN
ALTER TABLE
  clubs
ADD
  COLUMN is_mcdo_pool BOOLEAN DEFAULT false;

END IF;

END $ $;